/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicContactRouteImport } from './routes/_public/contact'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin/orders/index'
import { Route as AdminCategoriesIndexRouteImport } from './routes/admin/categories/index'
import { Route as AdminCarouselIndexRouteImport } from './routes/admin/carousel/index'
import { Route as PublicProductsIndexRouteImport } from './routes/_public/products/index'
import { Route as PublicCategoryIndexRouteImport } from './routes/_public/category/index'
import { Route as AdminProductsNewRouteImport } from './routes/admin/products/new'
import { Route as AdminCategoriesNewRouteImport } from './routes/admin/categories/new'
import { Route as AdminCarouselAddRouteImport } from './routes/admin/carousel/add'
import { Route as AdminCarouselCarouselIdRouteImport } from './routes/admin/carousel/$carouselId'
import { Route as PublicProductsProductIdRouteImport } from './routes/_public/products/$productId'
import { Route as PublicCategorySlugRouteImport } from './routes/_public/category/$slug'
import { Route as PubliccustomerOrdersRouteImport } from './routes/_public/(customer)/orders'
import { Route as PubliccustomerCheckoutRouteImport } from './routes/_public/(customer)/checkout'
import { Route as AdminProductsProductIdEditRouteImport } from './routes/admin/products/$productId.edit'
import { Route as AdminCarouselCarouselIdEditRouteImport } from './routes/admin/carousel/$carouselId.edit'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/_auth/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesIndexRoute = AdminCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCarouselIndexRoute = AdminCarouselIndexRouteImport.update({
  id: '/carousel/',
  path: '/carousel/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicProductsIndexRoute = PublicProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCategoryIndexRoute = PublicCategoryIndexRouteImport.update({
  id: '/category/',
  path: '/category/',
  getParentRoute: () => PublicRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesNewRoute = AdminCategoriesNewRouteImport.update({
  id: '/categories/new',
  path: '/categories/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCarouselAddRoute = AdminCarouselAddRouteImport.update({
  id: '/carousel/add',
  path: '/carousel/add',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCarouselCarouselIdRoute = AdminCarouselCarouselIdRouteImport.update({
  id: '/carousel/$carouselId',
  path: '/carousel/$carouselId',
  getParentRoute: () => AdminRoute,
} as any)
const PublicProductsProductIdRoute = PublicProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCategorySlugRoute = PublicCategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PubliccustomerOrdersRoute = PubliccustomerOrdersRouteImport.update({
  id: '/(customer)/orders',
  path: '/orders',
  getParentRoute: () => PublicRoute,
} as any)
const PubliccustomerCheckoutRoute = PubliccustomerCheckoutRouteImport.update({
  id: '/(customer)/checkout',
  path: '/checkout',
  getParentRoute: () => PublicRoute,
} as any)
const AdminProductsProductIdEditRoute =
  AdminProductsProductIdEditRouteImport.update({
    id: '/products/$productId/edit',
    path: '/products/$productId/edit',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCarouselCarouselIdEditRoute =
  AdminCarouselCarouselIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AdminCarouselCarouselIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/checkout': typeof PubliccustomerCheckoutRoute
  '/orders': typeof PubliccustomerOrdersRoute
  '/category/$slug': typeof PublicCategorySlugRoute
  '/products/$productId': typeof PublicProductsProductIdRoute
  '/admin/carousel/$carouselId': typeof AdminCarouselCarouselIdRouteWithChildren
  '/admin/carousel/add': typeof AdminCarouselAddRoute
  '/admin/categories/new': typeof AdminCategoriesNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/category': typeof PublicCategoryIndexRoute
  '/products': typeof PublicProductsIndexRoute
  '/admin/carousel': typeof AdminCarouselIndexRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/carousel/$carouselId/edit': typeof AdminCarouselCarouselIdEditRoute
  '/admin/products/$productId/edit': typeof AdminProductsProductIdEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/checkout': typeof PubliccustomerCheckoutRoute
  '/orders': typeof PubliccustomerOrdersRoute
  '/category/$slug': typeof PublicCategorySlugRoute
  '/products/$productId': typeof PublicProductsProductIdRoute
  '/admin/carousel/$carouselId': typeof AdminCarouselCarouselIdRouteWithChildren
  '/admin/carousel/add': typeof AdminCarouselAddRoute
  '/admin/categories/new': typeof AdminCategoriesNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/category': typeof PublicCategoryIndexRoute
  '/products': typeof PublicProductsIndexRoute
  '/admin/carousel': typeof AdminCarouselIndexRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/carousel/$carouselId/edit': typeof AdminCarouselCarouselIdEditRoute
  '/admin/products/$productId/edit': typeof AdminProductsProductIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_public/(customer)/checkout': typeof PubliccustomerCheckoutRoute
  '/_public/(customer)/orders': typeof PubliccustomerOrdersRoute
  '/_public/category/$slug': typeof PublicCategorySlugRoute
  '/_public/products/$productId': typeof PublicProductsProductIdRoute
  '/admin/carousel/$carouselId': typeof AdminCarouselCarouselIdRouteWithChildren
  '/admin/carousel/add': typeof AdminCarouselAddRoute
  '/admin/categories/new': typeof AdminCategoriesNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/_public/category/': typeof PublicCategoryIndexRoute
  '/_public/products/': typeof PublicProductsIndexRoute
  '/admin/carousel/': typeof AdminCarouselIndexRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/carousel/$carouselId/edit': typeof AdminCarouselCarouselIdEditRoute
  '/admin/products/$productId/edit': typeof AdminProductsProductIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/login'
    | '/register'
    | '/about'
    | '/contact'
    | '/'
    | '/admin/'
    | '/checkout'
    | '/orders'
    | '/category/$slug'
    | '/products/$productId'
    | '/admin/carousel/$carouselId'
    | '/admin/carousel/add'
    | '/admin/categories/new'
    | '/admin/products/new'
    | '/category'
    | '/products'
    | '/admin/carousel'
    | '/admin/categories'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/carousel/$carouselId/edit'
    | '/admin/products/$productId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/about'
    | '/contact'
    | '/'
    | '/admin'
    | '/checkout'
    | '/orders'
    | '/category/$slug'
    | '/products/$productId'
    | '/admin/carousel/$carouselId'
    | '/admin/carousel/add'
    | '/admin/categories/new'
    | '/admin/products/new'
    | '/category'
    | '/products'
    | '/admin/carousel'
    | '/admin/categories'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/carousel/$carouselId/edit'
    | '/admin/products/$productId/edit'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/_auth/login'
    | '/_auth/register'
    | '/_public/about'
    | '/_public/contact'
    | '/_public/'
    | '/admin/'
    | '/_public/(customer)/checkout'
    | '/_public/(customer)/orders'
    | '/_public/category/$slug'
    | '/_public/products/$productId'
    | '/admin/carousel/$carouselId'
    | '/admin/carousel/add'
    | '/admin/categories/new'
    | '/admin/products/new'
    | '/_public/category/'
    | '/_public/products/'
    | '/admin/carousel/'
    | '/admin/categories/'
    | '/admin/orders/'
    | '/admin/products/'
    | '/admin/carousel/$carouselId/edit'
    | '/admin/products/$productId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories/': {
      id: '/admin/categories/'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/carousel/': {
      id: '/admin/carousel/'
      path: '/carousel'
      fullPath: '/admin/carousel'
      preLoaderRoute: typeof AdminCarouselIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/products/': {
      id: '/_public/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof PublicProductsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/category/': {
      id: '/_public/category/'
      path: '/category'
      fullPath: '/category'
      preLoaderRoute: typeof PublicCategoryIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories/new': {
      id: '/admin/categories/new'
      path: '/categories/new'
      fullPath: '/admin/categories/new'
      preLoaderRoute: typeof AdminCategoriesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/carousel/add': {
      id: '/admin/carousel/add'
      path: '/carousel/add'
      fullPath: '/admin/carousel/add'
      preLoaderRoute: typeof AdminCarouselAddRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/carousel/$carouselId': {
      id: '/admin/carousel/$carouselId'
      path: '/carousel/$carouselId'
      fullPath: '/admin/carousel/$carouselId'
      preLoaderRoute: typeof AdminCarouselCarouselIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/products/$productId': {
      id: '/_public/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof PublicProductsProductIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/category/$slug': {
      id: '/_public/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof PublicCategorySlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/(customer)/orders': {
      id: '/_public/(customer)/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof PubliccustomerOrdersRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/(customer)/checkout': {
      id: '/_public/(customer)/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof PubliccustomerCheckoutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/products/$productId/edit': {
      id: '/admin/products/$productId/edit'
      path: '/products/$productId/edit'
      fullPath: '/admin/products/$productId/edit'
      preLoaderRoute: typeof AdminProductsProductIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/carousel/$carouselId/edit': {
      id: '/admin/carousel/$carouselId/edit'
      path: '/edit'
      fullPath: '/admin/carousel/$carouselId/edit'
      preLoaderRoute: typeof AdminCarouselCarouselIdEditRouteImport
      parentRoute: typeof AdminCarouselCarouselIdRoute
    }
  }
}

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PubliccustomerCheckoutRoute: typeof PubliccustomerCheckoutRoute
  PubliccustomerOrdersRoute: typeof PubliccustomerOrdersRoute
  PublicCategorySlugRoute: typeof PublicCategorySlugRoute
  PublicProductsProductIdRoute: typeof PublicProductsProductIdRoute
  PublicCategoryIndexRoute: typeof PublicCategoryIndexRoute
  PublicProductsIndexRoute: typeof PublicProductsIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicContactRoute: PublicContactRoute,
  PublicIndexRoute: PublicIndexRoute,
  PubliccustomerCheckoutRoute: PubliccustomerCheckoutRoute,
  PubliccustomerOrdersRoute: PubliccustomerOrdersRoute,
  PublicCategorySlugRoute: PublicCategorySlugRoute,
  PublicProductsProductIdRoute: PublicProductsProductIdRoute,
  PublicCategoryIndexRoute: PublicCategoryIndexRoute,
  PublicProductsIndexRoute: PublicProductsIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminCarouselCarouselIdRouteChildren {
  AdminCarouselCarouselIdEditRoute: typeof AdminCarouselCarouselIdEditRoute
}

const AdminCarouselCarouselIdRouteChildren: AdminCarouselCarouselIdRouteChildren =
  {
    AdminCarouselCarouselIdEditRoute: AdminCarouselCarouselIdEditRoute,
  }

const AdminCarouselCarouselIdRouteWithChildren =
  AdminCarouselCarouselIdRoute._addFileChildren(
    AdminCarouselCarouselIdRouteChildren,
  )

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCarouselCarouselIdRoute: typeof AdminCarouselCarouselIdRouteWithChildren
  AdminCarouselAddRoute: typeof AdminCarouselAddRoute
  AdminCategoriesNewRoute: typeof AdminCategoriesNewRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminCarouselIndexRoute: typeof AdminCarouselIndexRoute
  AdminCategoriesIndexRoute: typeof AdminCategoriesIndexRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminProductsProductIdEditRoute: typeof AdminProductsProductIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminCarouselCarouselIdRoute: AdminCarouselCarouselIdRouteWithChildren,
  AdminCarouselAddRoute: AdminCarouselAddRoute,
  AdminCategoriesNewRoute: AdminCategoriesNewRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminCarouselIndexRoute: AdminCarouselIndexRoute,
  AdminCategoriesIndexRoute: AdminCategoriesIndexRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminProductsProductIdEditRoute: AdminProductsProductIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
